### ISSUE TITLE
Introduce GitHub Actions

### ISSUE THREAD

**Issue by arturjaworski** [ably/asset-tracking-ios-rider-app-demo#15] opened 2022-07-12 10:27 UTC
We need to introduce GitHub Actions as CI to build Testflight builds.

**Comment by JakubJankowski** [comment] 2022-07-12 11:16
Duplicate of https://github.com/ably/asset-tracking-ios-rider-app-demo/issues/16

**Closed as completed by JakubJankowski** 2022-07-12 11:16 UTC
